apiVersion: v1
kind: Deployment
metadata:
  name: stackdriver-build-deployment
  labels:
    app: stackdriver-build
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackdriver-build
  template:
    metadata:
      labels:
        app: stackdriver-build
    spec:
      serviceAccountName: admin-user
      containers:
      - name: gcr.io/wise-diagram-197921/stackdriver-build
        image: gcr.io/wise-diagram-197921/stackdriver-build
        ports:
        - containerPort: 8080
